version: "3.5"
services:
  icons:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/icons
      - ~/.ssh/id_ed25519:/home/user/.ssh/id_ed25519
    env_file:
      - .env
